# Generated by Django 3.1 on 2020-09-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200930_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authy_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
