# Generated by Django 3.1 on 2020-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200930_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
