# Generated by Django 3.1 on 2020-09-30 21:26

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200930_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authy_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', django_cryptography.fields.encrypt(models.CharField(max_length=10))),
                ('authy_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
