# Generated by Django 3.1 on 2020-09-30 21:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authy_user',
            name='contact',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10, unique=True)),
        ),
    ]
